spring.application.name=task-api

spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=louisstiller
spring.datasource.password=
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update