spring.application.name=task-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:louisstiller}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.address=0.0.0.0
server.port=${PORT:8080}

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true